apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-trino-svc
  namespace: {{ .Release.Namespace}}
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
    nodePort: 30003
  selector:
    app: {{ .Release.Name}}-trino-coordinator
  type: NodePort
